In [105]:
import pandas as pd 
import numpy as np

In [163]:
ecom=pd.read_csv("ECommerce_Orders_.csv")
edata=pd.read_csv("Employee_Data_.csv")
student=pd.read_csv("Student_Performance.csv")

In [107]:
ecom.head()

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5
1,ORD002,Priya Reddy,Bangalore,Clothing,T-Shirt,2,1200,Card,4
2,ORD003,Arjun Kumar,Hyderabad,Electronics,Mobile,1,25000,UPI,5
3,ORD004,Sneha Rao,Chennai,Home,Mixer,1,5000,Cash,3
4,ORD005,Kiran Das,Pune,Electronics,Headphones,2,3000,Card,4

In [108]:
ecom["Sales"]=ecom["Quantity"]*ecom["Unit_Price"]

In [109]:
result = ecom[
    (ecom["Category"] == "Electronics") &
    (ecom["Sales"] > 20000 ) &
    (ecom["Rating"] >= 4) &
    (ecom["Payment_Mode"].isin(["UPI","Card"]))
]

In [110]:
result

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,Sales
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5,65000
2,ORD003,Arjun Kumar,Hyderabad,Electronics,Mobile,1,25000,UPI,5,25000
10,ORD011,Arjun Kumar,Hyderabad,Electronics,Tablet,1,30000,UPI,5,30000

In [111]:
#TASK=2
#Upper  case
ecom["Customer_upper"]=ecom["Customer"].str.upper()

In [112]:
ecom["First_name"]=ecom["Customer"].str.split().str[0]

In [113]:
result =ecom[ ecom["First_name"].str.startswith(("A","R"))
]

In [114]:
result[["Customer","First_name"]]

        Customer First_name
0   Rahul Sharma      Rahul
2    Arjun Kumar      Arjun
5   Rahul Sharma      Rahul
6   Anjali Singh     Anjali
9    Rohit Verma      Rohit
10   Arjun Kumar      Arjun
13  Anjali Singh     Anjali

In [115]:
result=ecom[ecom["Customer"].str.contains(
    "ra",
    case=False,
    na=False
)
]

In [116]:
case=False

In [117]:
ecom["Name_length"]=ecom["Customer"].str.len()

In [118]:
#task3
conditions=[ecom["Sales"]<5000,
            ecom["Sales"].between(5000,20000),
            ecom["Sales"].between(20000,50000),
            ecom["Sales"]>50000]

In [119]:
choices =[
    "Low",
    "Medium",
    "High",
    "Very High"
]

In [120]:
ecom.head()

,Order_ID,Customer,City,Category,Product,Quantity,Unit_Price,Payment_Mode,Rating,Sales,Customer_upper,First_name,Name_length
0,ORD001,Rahul Sharma,Hyderabad,Electronics,Laptop,1,65000,UPI,5,65000,RAHUL SHARMA,Rahul,12
1,ORD002,Priya Reddy,Bangalore,Clothing,T-Shirt,2,1200,Card,4,2400,PRIYA REDDY,Priya,11
2,ORD003,Arjun Kumar,Hyderabad,Electronics,Mobile,1,25000,UPI,5,25000,ARJUN KUMAR,Arjun,11
3,ORD004,Sneha Rao,Chennai,Home,Mixer,1,5000,Cash,3,5000,SNEHA RAO,Sneha,9
4,ORD005,Kiran Das,Pune,Electronics,Headphones,2,3000,Card,4,6000,KIRAN DAS,Kiran,9

In [121]:
ecom["Sales_Level"] =np.select(conditions,choices,default="Unclassified")

In [122]:
ecom["Customer_Type"]=np.where(
    ecom["Rating"] >=4,
    "Satisfied",
    "Need Attention"
)

In [123]:
ecom[["Order_ID",
      "Sales",
      "Rating",
      "Sales_Level",
      "Customer_Type"]]

   Order_ID  Sales  Rating Sales_Level   Customer_Type
0    ORD001  65000       5   Very High       Satisfied
1    ORD002   2400       4         Low       Satisfied
2    ORD003  25000       5        High       Satisfied
3    ORD004   5000       3      Medium  Need Attention
4    ORD005   6000       4      Medium       Satisfied
5    ORD006   2200       5         Low       Satisfied
6    ORD007  18000       4      Medium       Satisfied
7    ORD008  15000       3      Medium  Need Attention
8    ORD009   2500       4         Low       Satisfied
9    ORD010   4500       5         Low       Satisfied
10   ORD011  30000       5        High       Satisfied
11   ORD012   3500       4         Low       Satisfied
12   ORD013   3600       3         Low  Need Attention
13   ORD014  12000       5      Medium       Satisfied
14   ORD015   2400       4         Low       Satisfied

In [124]:
#task 4
result=ecom[
    ecom["Product"].str.contains(
        "phone",
        case=False,
        na=False
    )
]

In [125]:
result[["Order_ID","Product","Category"]]

  Order_ID     Product     Category
4   ORD005  Headphones  Electronics

In [126]:
result=ecom[
    ecom["Product"].str.contains(
        "lap|tab",
        case=False,
        na=False
    )
]

In [127]:
result=ecom[
    ecom["Category"].str.len()>6
]

In [128]:
result=ecom[
    ecom["Product"].str.contains(
        "lap|tab|phone",
        case="False",
        na=False
    )
    &
    (ecom["Product"].str.len()>6)
    &
    (ecom["Category"] != "Clothing")
]

In [129]:
result[["Order_ID","Product","Category"]]

  Order_ID     Product     Category
4   ORD005  Headphones  Electronics

In [130]:
conditions=[
    ecom["Unit_Price"]<2000,
    ecom["Unit_Price"].between(2000,10000),
    ecom["Unit_Price"].between(10000,30000),
    ecom["Unit_Price"]>30000
]
choices=[
    "Budget",
    "Mid Range",
    "Premium",
    "Luxury"
]
ecom["Price_Category"]=np.select(
    conditions,
    choices,
    default="Unclassified"
)

In [131]:
ecom[["Product","Unit_Price","Price_Category"]]

       Product  Unit_Price Price_Category
0       Laptop       65000         Luxury
1      T-Shirt        1200         Budget
2       Mobile       25000        Premium
3        Mixer        5000      Mid Range
4   Headphones        3000      Mid Range
5        Jeans        2200      Mid Range
6      Monitor       18000        Premium
7        Chair        7500      Mid Range
8        Shoes        2500      Mid Range
9     Keyboard        1500         Budget
10      Tablet       30000        Premium
11      Jacket        3500      Mid Range
12        Lamp        1800         Budget
13  Smartwatch       12000        Premium
14     T-Shirt        1200         Budget

In [132]:
result=ecom[
    (ecom["Price_Category"]=="Luxury")
    &
    (ecom["Quantity"]>1)
]

In [133]:
result=result.sort_values(
    "Unit_Price",
    ascending=False
)

In [134]:
result[[
    "Product",
    "Category",
    "Quantity",
    "Unit_Price",
    "Price_Category"
]]

Empty DataFrame
Columns: [Product, Category, Quantity, Unit_Price, Price_Category]
Index: []

In [135]:
#task6

edata
result=edata.loc[
    (edata["Department"]=="IT") &
    (edata["Experience"] >= 5) &
    (edata["Performance"] >= 4.3) &
    (edata["Salary"] >= 70000),
    [
        "Employee_ID",
        "Name",
        "Experience",
        "Salary",
        "Performance"
    ]
]

In [136]:
result=result.sort_values(
    "Performance",
    ascending=False
)

In [137]:
result

    Employee_ID    Name  Experience  Salary  Performance
11          112    Amit           6   80000          4.9
5           106  Anjali           6   85000          4.7
9           110  Suresh           5   70000          4.3

In [138]:
#Task 7
conditions=[
    edata["Salary"] < 60000,
    edata["Salary"].between(60000,75000),
    edata["Salary"].between(75000,90000),
    edata["Salary"] > 90000
]
choices=[
    "Entry",
    "Mid",
    "Senior",
    "Lead"
]
edata["Salary_Bond"]=np.select(
    conditions,
    choices,
    default="Unclassified"
)

In [139]:
edata["Promotion_Flag"]=np.where(
    (edata["Experience"] >=5) &
    (edata["Performance"] >=45),
    "Reveiw",
    "No Review"
     
)

In [140]:
result = edata[
    edata["Promotion_Flag"] == "Review"
]

In [141]:
result[
    [
        "Name",
        "Department",
        "Experience",
        "Salary",
        "Performance",
        "Salary_Bond",
        "Promotion_Flag"
    ]
]

Empty DataFrame
Columns: [Name, Department, Experience, Salary, Performance, Salary_Bond, Promotion_Flag]
Index: []

In [142]:
#Task 8
#creating duplicate dataset
dirty_emp=edata.copy()

In [143]:
dirty_emp.loc[2,"Salary"]=np.nan

In [144]:
dirty_emp.loc[5,"Department"]=np.nan

In [145]:
dirty_emp=pd.concat(
    [dirty_emp,dirty_emp.loc[[1]]],
    ignore_index=True
)

In [146]:
dirty_emp.isna().sum()

Employee_ID       0
Name              0
Department        1
Experience        0
Salary            1
Performance       0
Salary_Bond       0
Promotion_Flag    0
dtype: int64

In [147]:
dirty_emp[dirty_emp.duplicated(keep=False)]

,Employee_ID,Name,Department,Experience,Salary,Performance,Salary_Bond,Promotion_Flag
1,102,Priya,HR,5,75000.0,4.2,Mid,No Review
12,102,Priya,HR,5,75000.0,4.2,Mid,No Review

In [148]:
dirty_emp=dirty_emp.drop_duplicates()

In [149]:
dirty_emp["Salary"]=dirty_emp["Salary"].fillna(dirty_emp["Salary"].median)

In [150]:
dirty_emp["Department"]=dirty_emp["Department"].fillna("unkonwn")

In [151]:
dirty_emp.isna().sum()

Employee_ID       0
Name              0
Department        0
Experience        0
Salary            0
Performance       0
Salary_Bond       0
Promotion_Flag    0
dtype: int64

In [152]:
dirty_emp.duplicated().sum()

0

In [153]:
student

  Student_ID    Name      Course  Attendance  Assignment_Score  Exam_Score
0       S001   Rahul      Python          92                85          88
1       S002   Priya      Python          85                78          80
2       S003   Arjun  JavaScript          78                65          70
3       S004   Sneha      Python          95                92          94
4       S005   Kiran         SQL          88                88          91
5       S006  Anjali      Python          91                90          93
6       S007  Vikram         SQL          72                60          58
7       S008   Rohit  JavaScript          89                75          78
8       S009   Meena      Python          96                95          96
9       S010   Pooja         SQL          80                82          85

In [154]:
student["Final_Score"]=(
    student["Assignment_Score"]*0.40+student["Exam_Score"]*0.60)

In [155]:
student[
    ["Name", "Assignment_Score", "Exam_Score", "Final_Score"]
]

     Name  Assignment_Score  Exam_Score  Final_Score
0   Rahul                85          88         86.8
1   Priya                78          80         79.2
2   Arjun                65          70         68.0
3   Sneha                92          94         93.2
4   Kiran                88          91         89.8
5  Anjali                90          93         91.8
6  Vikram                60          58         58.8
7   Rohit                75          78         76.8
8   Meena                95          96         95.6
9   Pooja                82          85         83.8

In [157]:
conditions=[
    student["Final_Score"] >= 85,
    student["Final_Score"].between(70,84.999),
    student["Final_Score"].between(50,69.999),
    student["Final_Score"] <50
]
choices=[
    "Excellent",
    "Good",
    "Need Improvement",
    "At Risk"
]
student["Status"]=np.select(
    conditions,
    choices,
    default="Unclassified"
)

In [158]:
result=student[
    (student["Attendance"] < 80) &
    (student["Final_Score"]<70)
]

In [160]:
result[
    [
        "Student_ID",
        "Name",
        "Course",
        "Attendance",
        "Final_Score",
        "Status"
    ]
]

  Student_ID    Name      Course  Attendance  Final_Score            Status
2       S003   Arjun  JavaScript          78         68.0  Need Improvement
6       S007  Vikram         SQL          72         58.8  Need Improvement

In [167]:
#Task 10
ecom["Revenue"]=(ecom["Quantity"])*(ecom["Unit_Price"])

In [169]:
conditions=[
    ecom["Revenue"]>=5000,
    ecom["Revenue"]>=2000
]

choices=[
    0.15,
    0.10
]
ecom["Discount_Rate"]=np.select(
    conditions,
    choices,
    default=0.05
)

In [170]:
ecom["Discount_Amount"]=(
    ecom["Revenue"]*
    ecom["Discount_Rate"]
)

In [171]:
ecom["Final_revenue"]=(
    ecom["Revenue"]*
    ecom["Discount_Amount"]
)

In [172]:
ecom["Customer_Status"]=np.where(
    ecom["Rating"] >=4,
    "Satisfied",
    "Needs_Attentions"
)

In [173]:
result=ecom[
    (ecom["Category"] == "Electronics")&
    (ecom["Final_revenue"] > 20000) &
    (ecom["Rating"] >= 4) &
    (ecom["Payment_Mode"] == "UPI")
    
]

In [175]:
result=result.sort_values(
    "Final_revenue",
    ascending=False
)

In [176]:
result = result[
    [
        "Order_ID",
        "Customer",
        "City",
        "Product",
        "Quantity",
        "Revenue",
        "Discount_Amount",
        "Final_revenue",
        "Rating"
    ]
]

In [ ]:
#Order label

ecom["Order_Label"]=(
    ecom["Order_ID"]
    + " - "
    +ecom["Product"]
    + " - $"
    +ecom["Revenue"].astype(int).astype(str)
)

In [178]:
print("\nQUALIFYING ORDERS")
print(result.to_string(index=False))

print("\nORDER LABELS")
print(
    ecom[
        ["Order_ID", "Order_Label"]
    ].to_string(index=False)
)

QUALIFYING ORDERS
Order_ID     Customer      City    Product  Quantity  Revenue  Discount_Amount  Final_revenue  Rating
  ORD001 Rahul Sharma Hyderabad     Laptop         1    65000           9750.0    633750000.0       5
  ORD011  Arjun Kumar Hyderabad     Tablet         1    30000           4500.0    135000000.0       5
  ORD003  Arjun Kumar Hyderabad     Mobile         1    25000           3750.0     93750000.0       5
  ORD014 Anjali Singh    Mumbai Smartwatch         1    12000           1800.0     21600000.0       5

ORDER LABELS
Order_ID                  Order_Label
  ORD001     ORD001 - Laptop - $65000
  ORD002     ORD002 - T-Shirt - $2400
  ORD003     ORD003 - Mobile - $25000
  ORD004       ORD004 - Mixer - $5000
  ORD005  ORD005 - Headphones - $6000
  ORD006       ORD006 - Jeans - $2200
  ORD007    ORD007 - Monitor - $18000
  ORD008      ORD008 - Chair - $15000
  ORD009       ORD009 - Shoes - $2500
  ORD010    ORD010 - Keyboard - $4500
  ORD011     ORD011 - Tablet - $30000
  ORD012      ORD012 - Jacket - $3500
  ORD013        ORD013 - Lamp - $3600
  ORD014 ORD014 - Smartwatch - $12000
  ORD015     ORD015 - T-Shirt - $2400

In [ ]:
result=ecom[
    (ecom["Category"] == "Electronics") &
    (ecom["Quantity"]>1)&
    (ecom["Rating"] >=4)&
    (ecom["Revenue"] > 100000)
]

In [181]:
result=result.sort_values(
    "Revenue",
    ascending=False
)

In [182]:
print(result)

   Order_ID      Customer       City     Product  Quantity  Revenue  \
0    ORD001  Rahul Sharma  Hyderabad      Laptop         1    65000
10   ORD011   Arjun Kumar  Hyderabad      Tablet         1    30000
2    ORD003   Arjun Kumar  Hyderabad      Mobile         1    25000
13   ORD014  Anjali Singh     Mumbai  Smartwatch         1    12000

    Discount_Amount  Final_revenue  Rating
0            9750.0    633750000.0       5
10           4500.0    135000000.0       5
2            3750.0     93750000.0       5
13           1800.0     21600000.0       5